<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>

<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">

    <div class="row invoice-preview">

      <!-- ================== INVOICE ================== -->
      <div class="col-xl-9 col-md-8 col-12 mb-md-0 mb-4">
        <div class="card invoice-preview-card">

          <!-- HEADER -->
          <div class="card-body">
            <div class="d-flex justify-content-between flex-xl-row flex-md-column flex-sm-row flex-column m-sm-3 m-0">

              <!-- LEFT (HOTEL SENDER) -->
              <div class="mb-xl-0 mb-4">
                <div class="d-flex svg-illustration mb-4 gap-2 align-items-center">
                  <span class="fw-bold fs-4">Hey Work</span>
                </div>
                <p class="mb-2">Hospitality Workforce System</p>
                <p class="mb-2">Indonesia</p>
                <p class="mb-0">finance@heywork.id</p>
              </div>

              <!-- RIGHT -->
              <div>
                <h4 class="fw-medium mb-2">
                  INVOICE #INV-<?= str_pad($invoice['id'], 6, '0', STR_PAD_LEFT) ?>
                </h4>

                <div class="mb-2 pt-1">
                  <span>Date Issued:</span>
                  <span class="fw-medium">
                    <?= date('F d, Y', strtotime($invoice['created_at'])) ?>
                  </span>
                </div>

                <div class="pt-1">
                  <span>Status:</span>
                  <span class="badge bg-label-warning">UNBILLED</span>
                </div>
              </div>

            </div>
          </div>

          <hr class="my-0" />

          <!-- BILL SECTION -->
          <div class="card-body">
            <div class="row p-sm-3 p-0">

              <!-- Invoice To -->
              <div class="col-xl-6 col-md-12 col-sm-5 col-12 mb-xl-0 mb-md-4 mb-sm-0 mb-4">
                <h6 class="mb-3">Invoice To:</h6>
                <p class="mb-1 fw-medium"><?= esc($invoice['hotel_name']) ?></p>
                <p class="mb-1">Hotel Finance Department</p>
                <p class="mb-0">finance@hotel.internal</p>
              </div>

              <!-- Bill To -->
              <div class="col-xl-6 col-md-12 col-sm-7 col-12">
                <h6 class="mb-4">Bill Summary:</h6>
                <table>
                  <tbody>
                    <tr>
                      <td class="pe-4">Total Due:</td>
                      <td class="fw-medium">
                        Rp<?= number_format($invoice['amount'], 0, ',', '.') ?>
                      </td>
                    </tr>
                    <tr>
                      <td class="pe-4">Payment Method:</td>
                      <td>Bank Transfer</td>
                    </tr>
                    <tr>
                      <td class="pe-4">Currency:</td>
                      <td>IDR</td>
                    </tr>
                  </tbody>
                </table>
              </div>

            </div>
          </div>

          <!-- ITEM TABLE -->
          <div class="table-responsive border-top">
            <table class="table m-0">
              <thead>
                <tr>
                  <th>Item</th>
                  <th>Description</th>
                  <th>Cost</th>
                  <th>Price</th>
                </tr>
              </thead>
              <tbody>

                <tr>
                  <td class="text-nowrap">Operational Expense</td>
                  <td class="text-nowrap"><?= esc($invoice['description']) ?></td>
                  <td>
                    Rp<?= number_format($invoice['amount'], 0, ',', '.') ?>
                  </td>
                  <td>
                    Rp<?= number_format($invoice['amount'], 0, ',', '.') ?>
                  </td>
                </tr>

                <!-- SUMMARY ROW -->
                <tr>
                  <td colspan="2" class="align-top px-4 py-4">
                    <p class="mb-2">
                      <span class="me-1 fw-medium">Generated By:</span>
                      <span><?= esc($invoice['hotel_name']) ?></span>
                    </p>
                    <span>This invoice is submitted for reimbursement.</span>
                  </td>

                  <td class="text-end pe-3 py-4">
                    <p class="mb-2 pt-3">Subtotal:</p>
                    <p class="mb-2">Discount:</p>
                    <p class="mb-2">Tax:</p>
                    <p class="mb-0 pb-3 fw-bold">Total:</p>
                  </td>

                  <td class="ps-2 py-4">
                    <p class="fw-medium mb-2 pt-3">
                      Rp<?= number_format($invoice['amount'], 0, ',', '.') ?>
                    </p>
                    <p class="fw-medium mb-2">Rp0</p>
                    <p class="fw-medium mb-2">Rp0</p>
                    <p class="fw-bold mb-0 pb-3">
                      Rp<?= number_format($invoice['amount'], 0, ',', '.') ?>
                    </p>
                  </td>
                </tr>

              </tbody>
            </table>
          </div>

          <!-- NOTE -->
          <div class="card-body mx-3">
            <div class="row">
              <div class="col-12">
                <span class="fw-medium">Note:</span>
                <span>
                  This invoice is generated automatically from debit transaction record in HeyWork system.
                </span>
              </div>
            </div>
          </div>

        </div>
      </div>
      <!-- ================== /INVOICE ================== -->


      <!-- ================== ACTIONS ================== -->
      <div class="col-xl-3 col-md-4 col-12 invoice-actions">
        <div class="card">
          <div class="card-body">

            <button
              class="btn btn-primary d-grid w-100 mb-2"
              data-bs-toggle="offcanvas"
              data-bs-target="#sendInvoiceOffcanvas">
              <span class="d-flex align-items-center justify-content-center text-nowrap"
                ><i class="ti ti-send ti-xs me-2"></i>Send Invoice</span
              >
            </button>

            <button class="btn btn-label-secondary d-grid w-100 mb-2">
              Download
            </button>

            <a href="<?= base_url('admin/invoices/print/'.$invoice['id']) ?>" 
               target="_blank"
               class="btn btn-primary w-100 mb-2">
               Print Invoice
            </a>

            <a href="<?= base_url('admin/invoices') ?>"
               class="btn btn-label-secondary d-grid w-100">
              Back
            </a>

          </div>
        </div>
      </div>
      <!-- ================== /ACTIONS ================== -->

    </div>

    <!-- Send Invoice Sidebar -->
    <div class="offcanvas offcanvas-end" id="sendInvoiceOffcanvas" tabindex="-1">
      <div class="offcanvas-header my-1">
        <h5 class="offcanvas-title">Send Invoice</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"></button>
      </div>

      <div class="offcanvas-body pt-0 flex-grow-1">
        <form id="sendInvoiceForm">

          <div class="mb-3">
            <label class="form-label">From</label>
            <input type="text"
                   class="form-control"
                   value="<?= esc($invoice['hotel_email']) ?>"
                   readonly />
          </div>

          <div class="mb-3">
            <label class="form-label">To</label>
            <input type="email"
                   class="form-control"
                   id="invoice_to"
                   value="finance@heywork.id" 
                   placeholder="hotel@email.com" />
          </div>

          <div class="mb-3">
            <label class="form-label">Subject</label>
            <input type="text"
                   class="form-control"
                   value="Invoice #INV-<?= str_pad($invoice['id'], 6, '0', STR_PAD_LEFT) ?>" />
          </div>

          <div class="mb-3">
            <label for="invoice-message" class="form-label">Message</label>
            <textarea disabled class="form-control" name="invoice-message" id="invoice-message" cols="3" rows="8">
Dear <?= esc($invoice['hotel_name']) ?>,

We have generated a new invoice in the amount of: Rp<?= number_format($invoice['amount'],0,',','.') ?>


Please find attached invoice for worker:
<?= esc($invoice['description']) ?>


Please process payment at your earliest convenience.

Regards,
HeyWork
            </textarea>
          </div>

          <div class="mb-4">
            <span class="badge bg-label-primary">
              <i class="ti ti-link ti-xs"></i>
              <span class="align-middle">Invoice Attached</span>
            </span>
          </div>

          <div class="d-flex">
            <a href="<?= base_url('admin/invoices/send/'.$invoice['id']) ?>" 
               class="btn btn-primary me-3">
               Send Invoice Email
            </a>
            
            <button type="button"
                    class="btn btn-label-secondary"
                    data-bs-dismiss="offcanvas">
              Cancel
            </button>
          </div>

        </form>
      </div>
    </div>

  </div>
</div>

<script>
function sendInvoice() {

    const email = document.getElementById('invoice_to').value;

    if (!email) {
        alert('Please enter recipient email');
        return;
    }

    alert('Invoice sent successfully to ' + email);

    const offcanvasEl = document.getElementById('sendInvoiceOffcanvas');
    const offcanvas = bootstrap.Offcanvas.getInstance(offcanvasEl);
    offcanvas.hide();
}
</script>
<?= $this->endSection() ?>